vich_uploader:
    db_driver: orm

    mappings:
        societes_logos:
            uri_prefix: /images/societes_logos
            upload_destination: '%kernel.project_dir%/public/images/societes_logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true

        users_avatars:
            uri_prefix: /images/users_avatars
            upload_destination: '%kernel.project_dir%/public/images/users_avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true
